CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(100),
	password VARCHAR(100),
	name VARCHAR(100),
	created_at TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scores (
	id SERIAL PRIMARY KEY,
	user_id INTEGER,
	score INTEGER,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_scores_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);